### ISSUE TITLE
this.$on,this.$emit,this.$off 跨页面没效果

### ISSUE THREAD

**Issue by zhhcho** [tvfe/wxpage#32]

**Comment by switer** [comment]
能确认 `this.$on` 是在 `this.$emit`之前执行吗

**Comment by zhhcho** [comment]
> 能确认`this.$on`是在`this.$emit`之前执行吗
我确实是先执行的派发。。   = =  谢谢你的提示，我对这块还不是很了解   不清楚监听一定要在  派发前执行。。。

**Comment by zhhcho** [comment]
> 能确认`this.$on`是在`this.$emit`之前执行吗

现在已经可以了   谢谢大大

**Comment by zhhcho** [comment]
> 能确认 `this.$on` 是在 `this.$emit`之前执行吗

**Comment by zhhcho** [comment]
> 能确认 `this.$on` 是在 `this.$emit`之前执行吗

> 
require('./lib/wxpage').A({
	extendPageBefore: function (name, page) {
		page.$test = function(){
			return 'ok';
		}
	},

> 通过这样挂载后   在页面中使用this.$test()  为什么会出现is not a function

> 挂载一个变量的话  在页面中打印也是只会出现undefined

**Comment by switer** [comment]
> 通过这样挂载后 在页面中使用this.$test() 为什么会出现is not a function

能展示下在哪个生命周期使用，与及完整的报错信息吗

**Comment by zhhcho** [comment]
> > 通过这样挂载后 在页面中使用this.$test() 为什么会出现is not a function
> 
> 能展示下在哪个生命周期使用，与及完整的报错信息吗

> **app.js**

> 
<pre>
require('./lib/wxpage').A({
	extendPageBefore: function (name, page) {
		page.$global = function (key, value) {
			var len = arguments.length
			if (len > 1) {
			getApp().globalData[key] = value
			} else if (len == 1) {
			return getApp().globalData[key]
			} else {
			return getApp().globalData
			}
		}
	},
	globalData:{
		test:'111'
	},
	config: {
		route: '/pages/$page',
	},
	onLaunch: function(opts) {
		// console.log('APP is Running', opts)
	},
	onShow: function () {
		// Do something
	},
})
</pre>

> **index.js**

> 
<pre>
var P = require('../lib/wxpage');
P('index', {
	...
	onLoad:function(){

		console.log(this.$global('test'));
                
                ...
</pre>

> **console**

>
<pre>
VM644:1 thirdScriptError
this.$global is not a function;at pages/index page lifeCycleMethod onLoad function
TypeError: this.$global is not a function
    at s.onLoad (http://127.0.0.1:13134/appservice/pages/index.js:22:20)
    at s.<anonymous> (http://127.0.0.1:13134/appservice/lib/wxpage.js:275:17)
    at s.<anonymous> (http://127.0.0.1:13134/appservice/lib/wxpage.js:275:17)
    at s.<anonymous> (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:696239)
    at s.__callPageLifeTime__ (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:696012)
    at Vt (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:714681)
    at Ht (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:715708)
    at Kt (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:717001)
    at Function.<anonymous> (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:718111)
    at pt.<anonymous> (http://127.0.0.1:13134/appservice/__dev__/WAService.js:1:683214)
</pre>

**Comment by switer** [comment]
`extendPageBefore`是在[config](https://github.com/tvfe/wxpage#%E7%A8%8B%E5%BA%8F-%E9%85%8D%E7%BD%AE)下的，因为不属于app的生命周期：

```js
A({
  config: {
    extendPageBefore: function (def, { fns }) {
      // ...
    }
  }
});
```

**Comment by zhhcho** [comment]
> `extendPageBefore`是在[config](https://github.com/tvfe/wxpage#%E7%A8%8B%E5%BA%8F-%E9%85%8D%E7%BD%AE)下的，因为不属于app的生命周期：
> 
> ```js
> A({
>   config: {
>     extendPageBefore: function (def, { fns }) {
>       // ...
>     }
>   }
> });
> ```
> 

> extendPageBefore,extendPageAfter这两个的用法能不能在文档中有详细的介绍。。。     这个实在有点看不懂 怎么用。。。
